version = 0.1
[default.deploy.parameters]
stack_name = "psych"
resolve_s3 = false
s3_prefix = "psych"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "psych-deploy"